// Blog article bodies (client-supplied copy, edited for grammar and UK spelling).
// Text supports **bold** for emphasis.

export type ArticleBlock =
  | { type: "p"; text: string }
  | { type: "h2"; text: string }
  | { type: "h3"; text: string }
  | { type: "list"; items: string[]; ordered?: boolean }
  | { type: "stats"; items: { value: string; label: string; source?: string }[] }
  | {
      type: "figure";
      src: string;
      alt: string;
      caption: string;
      width: number;
      height: number;
      dark?: boolean;
    }
  | { type: "table"; caption: string; head: string[]; rows: string[][] }
  | { type: "callout"; title: string; text: string };

export type Article = {
  intro: string;
  blocks: ArticleBlock[];
  takeaway: string;
};

export const articles: Record<string, Article> = {
  "family-offices-mena-challenges": {
    intro:
      "The dominance of family-owned businesses is more visible in the MENA region than in any other part of the world. Well-known family businesses in the region include Majid Al Futtaim, Al Ghurair, Al Ajlan, Al Olayan and many others, operating across investment and banking, retail and industrial services.",
    blocks: [
      {
        type: "p",
        text: "One of the main reasons these businesses are so dominant is their long history of trade in the region. At a time when digital technology was not yet common, visionary entrepreneurs and well-known tribal figures led the market. Another reason is the strong culture of unity in long-established family organisations, where business was built on family ties that last to this day.",
      },
      {
        type: "stats",
        items: [
          { value: "90%", label: "of companies in the Middle East are family-owned" },
          { value: "~80%", label: "of the region's GDP is generated by family businesses" },
          { value: "10,000", label: "family offices worldwide, half formed in the past 15 years", source: "EY" },
        ],
      },
      {
        type: "p",
        text: "The rapid growth of wealth worldwide can be traced to the spread of family-owned businesses and the growing number of ultra-high-net-worth individuals (UHNWIs). According to EY estimates, around 10,000 family offices exist around the world, and half of them were formed in the past 15 years.",
      },
      { type: "h2", text: "Why Growth Is Harder Than It Looks" },
      {
        type: "p",
        text: "Despite the rapid growth of family-owned businesses in MENA, running them is not as easy as it may seem from the outside. Their success could reach even greater heights, but it is held back largely by the practical difficulty of administering investment portfolios and funds across multiple sectors from a single family office. Managing generational wealth, and keeping it growing as business sectors constantly advance, is a demanding job that requires significant resources. Some of the challenges family offices in the MENA region commonly face include the following.",
      },
      { type: "h2", text: "1. Succession Planning" },
      {
        type: "stats",
        items: [
          {
            value: "69%",
            label: "of family offices in the Middle East and Africa have no standard succession or growth plan",
            source: "PwC",
          },
        ],
      },
      {
        type: "p",
        text: "According to a PwC survey, 69% of family offices in the Middle East and Africa have no standard succession or growth plan, which can lead families to lose their wealth by the third or fourth generation because business matters are left unregulated. **Succession planning** challenges are one of the biggest threats to family offices in this region, more than in any other part of the world. Reasons include a growing number of heirs and family members, each with their own vision and plans.",
      },
      {
        type: "p",
        text: "Family offices are therefore strongly encouraged to set a formal succession plan and clear governance structure that includes all board members and investment professionals. This bridges the communication gap between decision-makers and business units, resulting in a more comprehensive and effective vision for the future.",
      },
      {
        type: "figure",
        src: "/images/dashboards/workflow-approval-request.webp",
        alt: "Investera approval request showing an approval workflow from requester to approver, with approve, reject and delegate actions",
        caption:
          "Structured approval workflows in Investera Pro give every decision a clear owner and audit trail.",
        width: 1440,
        height: 900,
      },
      { type: "h2", text: "2. Bridging the Generation Gap" },
      {
        type: "p",
        text: "When an effective succession plan is in place, **bridging the generation gap** between the heirs of inherited wealth becomes easier. The generation gap is one of the most prominent challenges facing members of family offices. Because the wealth or business is inherited, many members want to keep running it \"as it is\" and \"preserve the legacy\", rather than adapting to new trends or refining the company's core values and goals.",
      },
      { type: "h2", text: "3. Making Peace with Technology" },
      {
        type: "p",
        text: "Another strong challenge in managing family office wealth is making peace with **technology**. Technology plays a major role in running family offices and managing their wealth. Despite the many benefits of systematic, automated work, the generation gap resurfaces here too: family members span different age groups, and their uneven interest in, or need for, technology can stand in the way of a proper succession plan and a shared vision. Some heirs from older generations are not tech-savvy or may not fully appreciate how essential it has become, especially in the world of numbers and investments.",
      },
      { type: "h2", text: "4. Growing Accounting Complexity" },
      {
        type: "p",
        text: "Facing increasing **accounting complexity** as investments and asset classes multiply over time is a challenging, day-to-day job. With an overflow of tasks, multiple portfolios to manage, large volumes of data and complex accounting requirements, the chance of error rises, which can result in significant losses of money and time.",
      },
      {
        type: "stats",
        items: [
          {
            value: "50%+",
            label: "of family office expenses in 2022 were internal operating costs",
            source: "UBS",
          },
          {
            value: "58.6 bps",
            label: "operating cost for family offices with USD 100–250 million in assets",
            source: "UBS",
          },
        ],
      },
      {
        type: "p",
        text: "According to UBS reports, internal operating costs accounted for over half of total family office expenses in 2022, varying with the size of the assets. For family offices with USD 100 million to USD 250 million in assets, for example, operating costs can reach 58.6 basis points.",
      },
      {
        type: "figure",
        src: "/images/blog/investor-dashboard.webp",
        alt: "Investera Pro consolidated dashboard showing IRR, totals, AUM breakdown by category and category allocation",
        caption:
          "A consolidated dashboard brings IRR, cash, liabilities and allocation across every entity into a single view.",
        width: 1440,
        height: 900,
      },
      {
        type: "p",
        text: "Task automation, robo-advisory and the deal pipelines that smart platforms provide can deliver more accurate information while saving time and cost. Research shows that many family offices increasingly face uncertainty in the financial markets, which is also linked to the complexity they deal with and a lack of visibility or solid ground to stand on.",
      },
      { type: "h2", text: "5. Security and Confidentiality" },
      {
        type: "p",
        text: "Another issue that can result from a weak relationship with technology is **security**. Managing years of accumulated wealth, monitoring investments and tracking financial holdings is always at risk of fraud and data breaches. Such data must be held confidentially, and this remains a concern for many investment offices. Without high-end cybersecurity, this information is always at risk, leading to losses of not only money but also opportunities.",
      },
      { type: "h2", text: "Conclusion: Embracing the Digital World" },
      {
        type: "p",
        text: "Family offices and their representatives must embrace the fast-paced, \"untraditional\" digital world we live in and move away from the idea that change means \"risking the legacy\". Adopting disruptive technologies such as blockchain and artificial intelligence is crucial to resolving almost all of the challenges they face. Implementing smart end-to-end ERP systems or AI-based business intelligence (BI) software can take investment and wealth management to a different level.",
      },
      {
        type: "callout",
        title: "Only 20% of professionals have smart tools",
        text: "According to a research survey on investment management, only 20% of industry professionals have access to smart business solutions that ease their workflow and let them manage funds and portfolios without daily complex tasks that increase the risk of error, fraud or data loss.",
      },
      {
        type: "p",
        text: "There are many smart investment management platforms available, such as Personal Capital, Investera Pro and many others. This software can help family offices meet their needs, handling multiple asset classes from private equity to public securities. At the click of a button, these technologies can manage fund workflows and transactions automatically, generate reports, build structures for growth, and even help investors see where they stand and how far they can grow within a given period, using dynamic dashboards and robo-advisory tools.",
      },
    ],
    takeaway:
      "Succession, generational change, technology adoption, accounting complexity and security are the defining challenges for MENA family offices. A connected investment platform addresses them together.",
  },

  "digital-assets-in-fintech": {
    intro:
      "Fintech refers to the dynamic intersection of financial services and technology. The rapid development of digital payment guidelines, policies and capabilities has substantially transformed the payments ecosystem, and it will not slow down any time soon.",
    blocks: [
      {
        type: "p",
        text: "The ever-evolving fintech industry opens up significant opportunities and simplifies business procedures. Transactions, purchases, banking, saving and investment processes have all changed dramatically over the past few decades, thanks to advances in the tech industry.",
      },
      {
        type: "p",
        text: "Although the rapidly evolving fintech industry offers numerous benefits, it also makes it critical for entrepreneurs and businesses to stay at the forefront as the payment ecosystem keeps expanding, and to adapt their businesses to the emerging trends reshaping the industry. This is where digital assets come in.",
      },
      { type: "h2", text: "What Are Digital Assets?" },
      {
        type: "p",
        text: "Digital assets are an older asset category, established more than a decade before cryptocurrencies. Everyday digital assets include Netflix streams, cloud photos and videos, documents and much more. A digital asset can be defined as a self-contained, valuable collection of binary data with a unique identifier that does not derive from a non-digital commodity.",
      },
      {
        type: "p",
        text: "Digital assets surround us, and their significance grows every day. Global economies rely heavily on the digital sector, as digital assets have virtually limitless development potential in a world of limited resources.",
      },
      {
        type: "p",
        text: "A new economic paradigm is already emerging as digital technologies such as blockchain, artificial intelligence (AI), the Internet of Things (IoT) and augmented reality (AR) combine with other elements of the industrial revolution, including 5G, robotics, 3D printing and drones. This has opened the space for a digital asset that could serve as a global standard, with a universal benchmark and store of value. The Banque de France and Meta's Libra were among the initiatives exploring digital currencies.",
      },
      {
        type: "figure",
        src: "/images/blog/portfolio-breakdown.webp",
        alt: "Investera portfolio breakdown table listing securities, number of shares, currency, entry price, current price and market value in AED",
        caption:
          "Whether holdings are listed, private or digital, a single portfolio view keeps value and exposure in one place.",
        width: 1600,
        height: 803,
        dark: true,
      },
      { type: "h2", text: "Types of Personal Digital Assets" },
      { type: "p", text: "Personal digital assets include a variety of items, including the following." },
      { type: "h3", text: "1. NFTs" },
      {
        type: "p",
        text: "NFTs have emerged as a new foundation of the digital economy in the investment ecosystem. One of the most talked-about digital assets, non-fungible tokens are similar to real-life art projects and can represent music, art, films, pictures or gaming avatars. An NFT carries a certificate of authenticity produced by the blockchain technology that also underpins several cryptocurrencies. Since their inception, NFTs have adapted to the fintech revolution and become an alternative way to buy and trade digital artwork.",
      },
      { type: "h3", text: "2. Blockchain" },
      {
        type: "p",
        text: "The technological solutions that enable digital assets are called blockchains. A blockchain lets a peer-to-peer network store information securely. It is a replicated public database, shared by many computers, to which new entries can be added but existing entries cannot be changed.",
      },
      {
        type: "p",
        text: "Industries use blockchain heavily in areas including insurance, funds and stock trading. With the help of machine learning, big data and artificial intelligence, blockchain has decentralised systems and reduced the risk of large-scale economic crises. It has also laid the groundwork for emerging technologies in digital finance, as it offers immutability, transparency and data protection.",
      },
      { type: "h3", text: "3. Cryptocurrency" },
      {
        type: "p",
        text: "The MENA region has made significant advances in digital assets with a host of new legal measures, and cryptocurrencies have become widely accepted in a very short time. Governments are taking the lead by introducing new laws, recognising that these digital assets will continue to grow in value.",
      },
      {
        type: "callout",
        title: "Regulation in the UAE",
        text: "Dubai formed the Virtual Assets Regulatory Authority (VARA) and passed new legislation to regulate virtual assets such as bitcoin and NFTs. These actions aim to legitimise a budding sector and pave the way for its expansion. The global crypto exchange FTX also obtained permission to operate in the UAE.",
      },
      { type: "h2", text: "Uses and Applications" },
      {
        type: "p",
        text: "Each of these digital assets has its own uses and applications. The table below summarises some of the most popular ones.",
      },
      {
        type: "table",
        caption: "Popular digital assets and how they are used",
        head: ["Digital asset", "What it is", "Common uses"],
        rows: [
          ["NFTs", "Unique tokens with a blockchain certificate of authenticity", "Digital art, music, films, gaming avatars and collectibles"],
          ["Blockchain", "A shared, append-only public database", "Insurance, funds, stock trading and secure record-keeping"],
          ["Cryptocurrency", "Digital currency secured by blockchain", "Payments, trading and regulated virtual asset services"],
        ],
      },
      {
        type: "p",
        text: "Digital assets can change ownership across decentralised networks without intermediaries, enabling faster and more affordable transactions, even globally. Converting physical goods into digital assets through tokenisation could therefore dramatically transform how we trade value. This decade, digital assets are expected to be a primary driver of sustainable economic growth.",
      },
    ],
    takeaway:
      "As digital assets become embedded in the world's financial systems and continue to disrupt fintech, keeping up with the latest policies and regulations is crucial for any ecosystem player that wants to lead.",
  },

  "proptech-disruptive-force-real-estate": {
    intro:
      "PropTech, short for \"property technology\", is a broad term for the many emerging technologies in the real estate sector, such as property management software, smart home devices and tools enabled by the Internet of Things (IoT). These technologies are also known as real estate tech, retech, realtech and CRE tech.",
    blocks: [
      {
        type: "p",
        text: "All of these technologies are designed to make deal sourcing, transaction processing, property management and customer service more efficient. In short, PropTech is where real estate and technology meet.",
      },
      {
        type: "p",
        text: "PropTech has become an innovative driver of disruptive technology, a solution for real estate professionals struggling with piles of paperwork, and a high-yield asset class for investors seeking opportunities. Over the last decade, real estate technology has evolved rapidly with the emergence of artificial intelligence (AI), augmented reality (AR) and virtual reality (VR). These advances meet the needs of real estate developers, operators, owners, tenants and investors. Property owners and operators can use real estate technology to manage their assets more effectively, as it reduces paperwork, simplifies transactions, enhances property management services and maximises operational efficiency.",
      },
      {
        type: "stats",
        items: [
          { value: "$18.2bn", label: "global PropTech market size in 2022" },
          { value: "$86.5bn", label: "projected market size by 2032" },
          { value: "16.8%", label: "compound annual growth rate (CAGR)" },
        ],
      },
      {
        type: "p",
        text: "The PropTech market is expected to grow from $18.2 billion in 2022 to $86.5 billion in 2032, a CAGR of 16.8%.",
      },
      {
        type: "p",
        text: "In the past few years, real estate brokers have increasingly used VR to give prospective buyers virtual property tours. Buyers can view properties from the comfort of their homes and pre-screen their options before visiting in person.",
      },
      {
        type: "p",
        text: "Examples of disruptive real estate technology include investment platforms that connect investors with real estate assets, and property management platforms for residential, office and retail properties. Founded in 2008, Airbnb, one of the earliest real estate technology companies, operates an online marketplace for short-term homestays and experiences, and has achieved huge success with listings in more than 220 countries and regions.",
      },
      {
        type: "figure",
        src: "/images/blog/consolidated-dashboard.webp",
        alt: "Investera Pro consolidated dashboard with IRR, totals and AUM breakdown by category including real estate",
        caption:
          "Real estate holdings sit alongside capital markets, private equity and cash in a consolidated Investera Pro dashboard.",
        width: 1600,
        height: 867,
      },
      { type: "h2", text: "How PropTech Connects with Other Industries" },
      {
        type: "list",
        items: [
          "**Shared economy:** any PropTech platform that offers shared use of a property, such as short-term rentals. Airbnb and WeWork are among the top players driving the sharing economy in the PropTech market.",
          "**Smart real estate:** internet-connected devices and appliances (IoT devices) that enable remote monitoring and management of smart homes. Amazon's Alexa, Siemens' smart kitchen appliances and Philips' intelligent lighting systems are well-known examples.",
          "**Fintech:** technology that makes financial services easier to access for customers and businesses. Real estate fintech focuses on the financial processes of the property industry. US-based home marketplace Zillow is disrupting PropTech as a fintech provider, simplifying home buying with faster transactions, lower costs and greater volume.",
          "**Construction technology:** modern materials and sustainable approaches, such as drones, Building Information Modelling (BIM) software and 3D printing, used to build real estate assets. OpenSpace, for example, is an AI-driven photo documentation tool that automatically creates navigable images of construction sites from cameras attached to workers' helmets.",
        ],
      },
      { type: "h2", text: "PropTech in the MENA Region" },
      {
        type: "p",
        text: "Over the last decade, the MENA region has shown high potential for deploying AI across real estate. In 2022, Realiste, a leading AI-based real estate development start-up, expanded into the Middle East, incorporating cutting-edge technology across its operations. The company's mission is to digitise every major city's real estate market while providing free appraisals and tailored services.",
      },
      {
        type: "p",
        text: "In 2021, leading PropTech platform Property Finder introduced MENA's first AI-driven agent rating system, \"SuperAgent\", supported by its Agent Data Assistant (ADA). ADA is an internal data platform that combines agent responsiveness, listing quality and agent reports to help buyers find relevant brokers.",
      },
      {
        type: "p",
        text: "Although MENA has been slower to adopt and invest in PropTech than leading markets such as the US, China and Europe, there are numerous opportunities for growth, and investor and entrepreneur activity has risen sharply since 2018. The UAE and Saudi Arabia lead the region's PropTech activity, and the UAE is recognised as its PropTech innovation hub.",
      },
      {
        type: "stats",
        items: [
          { value: "100,000", label: "coders to be trained under Dubai's national programme" },
          { value: "1,000", label: "digital companies to be established over five years" },
          { value: "Dhs4bn", label: "start-up investment target, up from Dhs1.5bn" },
        ],
      },
      {
        type: "p",
        text: "In 2021, Dubai launched a national programme to train 100,000 coders and establish 1,000 digital companies over five years, aiming to increase start-up investment from Dhs1.5 billion to Dhs4 billion. With initiatives like these, government support for digital transformation is likely to be the main driver of PropTech growth in the country.",
      },
      {
        type: "p",
        text: "Eltizam Group's technology division, EAST-O Holdings, recently launched PropEzy, a cloud-based software-as-a-service (SaaS) platform for managing customer experience and optimising operations in the region's real estate management sector. The UAE-based app brings the technology platforms used to manage the built environment into a single integrated product, reducing costs and increasing ROI for asset owners and operators.",
      },
      {
        type: "figure",
        src: "/images/blog/deal-pipeline.webp",
        alt: "Investera deal pipeline dashboard showing open, won and dropped deals across screening, evaluation and due diligence stages",
        caption:
          "From screening to due diligence, a deal pipeline keeps property and other investment opportunities moving.",
        width: 1178,
        height: 702,
      },
      { type: "h3", text: "Metaverse and NFTs" },
      {
        type: "p",
        text: "Metaverse technology and NFTs are also expanding in the region. In 2022, Dubai-based Union Square House (USH) announced plans to launch MENA's first metaverse mansions, selling luxury properties as NFTs with or without physical counterparts. Digital versions of the properties would be available in the metaverse as places to relax, entertain guests or decorate. This sits alongside Dubai's Metaverse Strategy, which aims to add 40,000 jobs, making the metaverse an increasingly important consideration for real estate developers in MENA's PropTech environment.",
      },
      { type: "h3", text: "AI in Valuation and Transactions" },
      {
        type: "p",
        text: "AI applications are growing every day in MENA's real estate market, accelerating growth and innovation in the region's PropTech industry. These include solutions that improve property management and support transactions and valuations. One example is the Dubai Land Department's (DLD) use of AI in valuing real estate assets. Through its smart channels, website and Dubai REST app, DLD is expanding its digital services, fostering digitisation and bringing greater efficiency and transparency to real estate operations. In 2021, DLD launched electronic no-objection certificates (e-NOCs) to reduce costs and speed up the process. Big data analytics is also on the rise, helping architects with initial design concepts and iterations.",
      },
      { type: "h3", text: "Smart Buildings and Smart Cities" },
      {
        type: "p",
        text: "The MENA region is known for its enthusiasm for smart buildings and smart cities, projects that often involve PropTech. Smart buildings gather and analyse data to future-proof structures within cities, often with IoT devices and appliances that automate, regulate and deliver essential utilities. Saudi Arabia's NEOM is a prime example of AI in PropTech: its development uses AI to operate machine-executable legislation, conduct inspections and provide projections and insights for data-driven decisions.",
      },
      {
        type: "p",
        text: "Dubai's Expo City is another project that puts PropTech in perspective. Its Internet of Things ecosystem uses a wide range of sensors, systems, gateways and building management applications that collect data across the site. After automated analysis, the system makes decisions on its own, maintaining ideal conditions for water use, air conditioning, lighting and energy consumption.",
      },
      { type: "h2", text: "Outlook" },
      {
        type: "p",
        text: "Although the industry has adapted quickly and the outlook is positive, PropTech is still in its infancy compared with other technology markets such as fintech. With a focus on smart, virtual and contactless technologies, PropTech trends are expected to accelerate in the coming years.",
      },
    ],
    takeaway:
      "PropTech companies in the MENA region have a chance to capitalise early by identifying and closing market gaps and developing relevant solutions for regional markets.",
  },
};

/** Plain text of an article, for reading-time estimates and AI summaries. */
export function articleText(article: Article) {
  const parts = [article.intro];
  for (const block of article.blocks) {
    if (block.type === "p" || block.type === "h2" || block.type === "h3") parts.push(block.text);
    if (block.type === "list") parts.push(...block.items);
    if (block.type === "callout") parts.push(block.title, block.text);
    if (block.type === "stats") parts.push(...block.items.map((s) => `${s.value} ${s.label}`));
    if (block.type === "table") parts.push(...block.rows.map((r) => r.join(" – ")));
  }
  parts.push(article.takeaway);
  return parts.join("\n\n").replace(/\*\*/g, "");
}
